### ISSUE TITLE
Resonite

### ISSUE THREAD

**Issue by troyBORG** [rassi0429/MessageCopy#8]
Can this be ported over for Resonite please!!!

**Comment by rassi0429** [comment]
OKOKOOOKOKOKOKO

**Comment by troyBORG** [comment]
Oh looks like it is no longer needed.  
Resonite Update [2023.10.13.202](https://discord.com/channels/1040316820650991766/1154514012143362151/1162231319774908456) 
```

Added copy button for text messages (I've been busy sorting out a bunch of Patreon linking issues and I need to copy some diagnostic data we get through the bot, so I really needed this one)
-- To copy message, hover over it, which will make a copy button appear
```

**Comment by rassi0429** [comment]
Thank you Frooxius san
This is the update
tears are flowing
